Specifying to only test in `tests` directory broke importing
```
Traceback (most recent call last):
  File "/Users/saul/.virtualenvs/django-canadanewyork/lib/python2.7/site-packages/django/core/management/base.py", line 222, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/saul/.virtualenvs/django-canadanewyork/lib/python2.7/site-packages/django/core/management/commands/test.py", line 72, in execute
    super(Command, self).execute(*args, **options)
  File "/Users/saul/.virtualenvs/django-canadanewyork/lib/python2.7/site-packages/django/core/management/base.py", line 255, in execute
    output = self.handle(*args, **options)
  File "/Users/saul/.virtualenvs/django-canadanewyork/lib/python2.7/site-packages/south/management/commands/test.py", line 8, in handle
    super(Command, self).handle(*args, **kwargs)
  File "/Users/saul/.virtualenvs/django-canadanewyork/lib/python2.7/site-packages/django/core/management/commands/test.py", line 89, in handle
    failures = test_runner.run_tests(test_labels)
  File "/Users/saul/.virtualenvs/django-canadanewyork/lib/python2.7/site-packages/discover_runner/runner.py", line 153, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "/Users/saul/.virtualenvs/django-canadanewyork/lib/python2.7/site-packages/discover_runner/runner.py", line 102, in build_suite
    tests = self.test_loader.discover(start_dir=label, **kwargs)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 202, in discover
    raise ImportError('Start directory is not importable: %r' % start_dir)
ImportError: Start directory is not importable: '/Users/saul/projects/django-canadanewyork'
```

so instead just call the `test` command with the `tests` directory